json.diagnostic_test_id diagnostic_test.id
json.standard_id diagnostic_test.standard_id
json.subject_id diagnostic_test.subject_id
json.string_name diagnostic_test.string_name
json.personalization_type diagnostic_test.personalization_type